const MESSAGES = {
  COMMANDS: {
    ADMIN: {
      CONFIG: {
        name: "config",
        aliases: ["config"],
        category: "admin",
        description: "Modifier la base de données",
        cooldown: 3,
        usage: "<key> <value>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      LOCKDOWN: {
        name: "lockdown",
        aliases: ["lockdown", "ldwn"],
        category: "admin",
        description: "Ferme le serveur",
        cooldown: 0.1,
        usage: "<on/off>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      LOCK: {
        name: "lock",
        aliases: ["lock", "lck"],
        category: "admin",
        description: "Ferme un certain salon",
        cooldown: 0.1,
        usage: "<on/off> <channel_id>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      PERMA: {
        name: "perma",
        aliases: ["perma"],
        category: "admin",
        description: "Crée une invitation permanante",
        cooldown: 10,
        usage: "",
        isUserAdmin: false,
        permissions: true,
        args: false,
      },
    },
    FUN: {
      CAT: {
        name: "cat",
        aliases: ["cat", "chat"],
        category: "fun",
        description: "Renvoie une image de chat",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },
      DOG: {
        name: "dog",
        aliases: ["dog", "chien"],
        category: "fun",
        description: "Renvoie une image de chien",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },
      FOX: {
        name: "fox",
        aliases: ["fox", "renard"],
        category: "fun",
        description: "Renvoie une image de renard",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },
      ANIME: {
        name: "anime",
        aliases: ["anime", "memes"],
        category: "fun",
        description: "Renvoie un meme de type anime",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },
    },
    MISC: {
      EIGHTBALL: {
        name: "8ball",
        aliases: ["8ball"],
        category: "misc",
        description: "Renvoie une réponse à une question",
        cooldown: 10,
        usage: "<question>",
        isUserAdmin: false,
        permissions: false,
        args: true,
      },

      SAY: {
        name: "say",
        aliases: ["repeat", "rep"],
        category: "misc",
        description: "Repete le message d'un utilisateur",
        cooldown: 10,
        usage: "<votre_message>",
        isUserAdmin: false,
        permissions: false,
        args: true,
      },

      COLOR: {
        name: "color",
        aliases: ["color"],
        category: "misc",
        description: "Génère une couleur aléatoire",
        cooldown: 10,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },

      INVITE: {
        name: "invite",
        aliases: ["invite"],
        category: "misc",
        description:
          "Envoie des informations par rapport aux invitations du serveur",
        cooldown: 10,
        usage: "<deleteall/view>",
        isUserAdmin: false,
        permissions: false,
        args: true,
      },

      PING: {
        name: "ping",
        aliases: ["ping"],
        category: "misc",
        description: "Renvoie pong",
        cooldown: 10,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },

      POLL: {
        name: "poll",
        aliases: ["poll", "sondage"],
        category: "misc",
        description: "Renvoie un sondage",
        cooldown: 10,
        usage: "<sondage>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      ADVERT: {
        name: "advert",
        aliases: ["advert"],
        category: "misc",
        description: "Permet de créer une annonce",
        cooldown: 10,
        usage: "<fr/en> <objet> <message>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      STATS: {
        name: "stats",
        aliases: ["stats"],
        category: "misc",
        description: "Envoie des statistiques",
        cooldown: 4,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },

      PUBON: {
        name: "pubon",
        aliases: ["pubon"],
        category: "misc",
        description: "Autoriser les pubs pour un utilisateur",
        cooldown: 10,
        usage: "<@user>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      PUBOFF: {
        name: "puboff",
        aliases: ["puboff"],
        category: "misc",
        description:
          "Interdire les pubs pour un utilisateur ayant été autorisé auparavant",
        cooldown: 10,
        usage: "<@user>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },
    },
    MODERATION: {
      BAN: {
        name: "ban",
        aliases: ["ban"],
        category: "moderation",
        description: "Ban un utilisateur",
        cooldown: 10,
        usage: "<@user> [reason]",
        isUserAdmin: true,
        permissions: true,
        args: true,
      },

      KICK: {
        name: "kick",
        aliases: ["kick"],
        category: "moderation",
        description: "Kick un utilisateur",
        cooldown: 10,
        usage: "<@user> [reason]",
        isUserAdmin: true,
        permissions: true,
        args: true,
      },

      MUTE: {
        name: "mute",
        aliases: ["mute"],
        category: "moderation",
        description: "Mute un utilisateur",
        cooldown: 10,
        usage: "<@user>",
        isUserAdmin: true,
        permissions: true,
        args: true,
      },

      PRUNE: {
        name: "prune",
        aliases: ["prune"],
        category: "moderation",
        description:
          "Purge un nombre de message spécifié sur un utilisateur spécifié",
        cooldown: 10,
        usage: "<@user> <nbr_messages>",
        isUserAdmin: true,
        permissions: true,
        args: true,
      },

      PURGE: {
        name: "purge",
        aliases: ["purge"],
        category: "moderation",
        description: "Purge un nombre de message spécifié",
        cooldown: 10,
        usage: "<nbr_messages>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      REPORT: {
        name: "report",
        aliases: ["report"],
        category: "moderation",
        description: "Report un utilisateur",
        cooldown: 10,
        usage: "<@user> [id_du_message] <raison>",
        isUserAdmin: false,
        permissions: false,
        args: true,
      },

      TEMPMUTE: {
        name: "tempmute",
        aliases: ["tempmute"],
        category: "moderation",
        description: "Mute un utilisateur temporairement",
        cooldown: 10,
        usage: "<@user> <time>",
        isUserAdmin: true,
        permissions: true,
        args: true,
      },

      TEMPBAN: {
        name: "tempban",
        aliases: ["tempban"],
        category: "moderation",
        description: "Ban un utilisateur temporairement",
        cooldown: 10,
        usage: "<@user> <time> [reason]",
        isUserAdmin: true,
        permissions: true,
        args: true,
      },

      UNBAN: {
        name: "unban",
        aliases: ["unban"],
        category: "moderation",
        description: "Unban un utilisateur",
        cooldown: 10,
        usage: "<user_id>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      UNMUTE: {
        name: "unmute",
        aliases: ["unmute"],
        category: "moderation",
        description: "Unmute un utilisateur",
        cooldown: 10,
        usage: "<@user>",
        isUserAdmin: true,
        permissions: true,
        args: true,
      },
    },
    REACTIONS: {
      EMOJI: {
        name: "emoji",
        aliases: ["emoji"],
        category: "reactions",
        description: "Renvoie des emojis sur notre message",
        cooldown: 0.1,
        usage: "<language/validate> <id>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },
    },
    COLLECTORS: {
      MSGCOLLECTOR: {
        name: "msgcollector",
        aliases: ["msgcollector", "mcol"],
        category: "collectors",
        description: "Message collector",
        cooldown: 3,
        usage: "<msg_to_collect>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      REACTCOLLECTOR: {
        name: "reactcollector",
        aliases: ["reactcollector", "rcol"],
        category: "collectors",
        description: "React collector",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: true,
        args: false,
      },
    },
    EXPERIENCE: {
      USEREXPERIENCE: {
        name: "userexperience",
        aliases: ["uexp", "userexperience"],
        category: "experience",
        description: "Renvoie l'éxperience de l'utilisateur",
        cooldown: 10,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },

      ADDEXPERIENCE: {
        name: "addexperience",
        aliases: ["addexp", "addexperience"],
        category: "experience",
        description: "Ajouter de l'éxperience à l'utilisateur",
        cooldown: 10,
        usage: "<@user> <exp_to_add>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      REMOVEEXPERIENCE: {
        name: "removeexperience",
        aliases: ["remexp", "removeexperience"],
        category: "experience",
        description: "Enlever de l'éxperience à l'utilisateur",
        cooldown: 10,
        usage: "<@user> <exp_to_remove>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },
    },
    OWNER: {
      EVAL: {
        name: "eval",
        aliases: ["eval"],
        category: "owner",
        description: "Renvoie un code JavaScript testé",
        cooldown: 3,
        usage: "<code>",
        isUserAdmin: false,
        permissions: true,
        args: true,
      },

      EMBED: {
        name: "embed",
        aliases: ["embed"],
        category: "owner",
        description: "Renvoie un embed",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: true,
        args: false,
      },

      RELOAD: {
        name: "reload",
        aliases: ["reload"],
        category: "owner",
        description: "Relancer le bot",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: true,
        args: false,
      },

      TEST: {
        name: "test",
        aliases: ["test"],
        category: "owner",
        description: "Tester plusieurs codes.",
        cooldown: 0.1,
        usage: "",
        isUserAdmin: false,
        permissions: true,
        args: false,
      },
    },
    INFORMATIONS: {
      USERINFO: {
        name: "userinfo",
        aliases: ["userinfo", "uinfo"],
        category: "informations",
        description: "Afficher les informations d'un membre.",
        cooldown: 3,
        usage: "<user>",
        isUserAdmin: false,
        permissions: false,
        args: true,
      },

      CHANNELINFO: {
        name: "channelinfo",
        aliases: ["channelinfo", "saloninfo"],
        category: "informations",
        description: "Afficher les informations d'un salon.",
        cooldown: 3,
        usage: "<channel>",
        isUserAdmin: false,
        permissions: false,
        args: true,
      },

      SERVERINFO: {
        name: "serverinfo",
        aliases: ["serverinfo", "guildinfo", "sinfo"],
        category: "informations",
        description: "Afficher les informations d'un serveur.",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },

      ROLEINFO: {
        name: "roleinfo",
        aliases: ["roleinfo", "gradeinfo", "rinfo"],
        category: "informations",
        description: "Afficher les informations d'un rôle.",
        cooldown: 3,
        usage: "<@role>",
        isUserAdmin: false,
        permissions: false,
        args: true,
      },
    },
    BOT: {
      HELP: {
        name: "help",
        aliases: ["help"],
        category: "bot",
        description:
          "Renvoie une liste de commandes ou les infurmations sur une seule.",
        cooldown: 3,
        usage: "<command_name>",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },

      UPTIME: {
        name: "uptime",
        aliases: ["uptime", "ping"],
        category: "bot",
        description: "Renvoie l'uptime du bot.",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },

      BOTINFO: {
        name: "botinfo",
        aliases: ["botinfo", "binfo"],
        category: "bot",
        description: "Afficher les informations sur le bot.",
        cooldown: 3,
        usage: "",
        isUserAdmin: false,
        permissions: false,
        args: false,
      },
    },
  },
};

exports.MESSAGES = MESSAGES;
